### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by iantbutler01** [virkillz/sveltex#2]
Hi there, so this is a nice little library, but without a license there's no real way I can in good conscience use this library in my code. I was wondering if you had considered adding a license? If you are considering it, I'm not qualified to advise you on which one is the best open source license to use but there are a few sites that can explain the pros and cons there.

See this thread for what not having a license in a Github repository means in terms of use:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by virkillz** [comment]
@iantbutler01 Good call! I just add the MIT license.

**Comment by iantbutler01** [comment]
@virkillz Hey awesome!
